services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "queue-pro-db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  backend:
    build:
      context: ./backend/
      dockerfile: ./Queue-Pro.API/Dockerfile
      
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AppDbContext=Host=db;Port=5432;Database=queue-pro-db;Username=postgres;Password=${POSTGRES_PASSWORD}
      - AuthSettings__SecretKey=${AUTH_SECRET_KEY}
      - AuthSettings__Expires=${AUTH_EXPIRES}
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  postgres-data: